version: '3'
services:
  db:
    build:
      context: ./docker/db/
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./municipalities:/municipalities
      - ./rivers:/rivers

volumes:
  postgresql_data:
